plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.gms.google.services)
}

android {
    namespace 'com.hotdesk.customercity'
    compileSdk 36

    defaultConfig {
        applicationId "com.hotdesk.customercity"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    // 1. ADD THIS SIGNING CONFIGS BLOCK
    signingConfigs {
        release {
            storeFile file("customercity.jks") // Looks inside the 'app' folder
            storePassword "customercity"      // Put your password here
            keyAlias "customercity_alias"
            keyPassword "customercity"        // Put your password here
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            // 2. ADD THIS LINE TO LINK THE SIGNING CONFIG
            signingConfig signingConfigs.release 
            
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}


dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.firebase.analytics
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.okhttp
    implementation libs.gson
    implementation libs.swiperefreshlayout
    implementation libs.drawerlayout
}